Repository KinsonDigital/PackageMonster, pull requests merged in 2023-04, with the labels that each got.

#49 🚧Setup codecov
  GotNuget.sln
  codecov.yml
Labels: medium priority, preview, ♻️cicd

#76 🚧Update the action output process
  .github/workflows/build-status-check.yml
  .github/workflows/unit-tests-status-check.yml
  GotNuget/GotNuget.csproj
  GotNuget/Guards/EnsureThat.cs
  GotNuget/Services/ActionOutputService.cs
  GotNuget/Services/EnvVarService.cs
  GotNuget/Services/IEnvVarService.cs
  Testing/GotNugetTests/GotNugetTests.csproj
  Testing/GotNugetTests/Guards/EnsureThatTests.cs
  Testing/GotNugetTests/Services/ActionOutputServiceTests.cs
Labels: high priority, preview

#79 🚧Fix issues with readme
  Documentation/Images/pkg-monster-logo.png
  LICENSE.md
  README.md
Labels: high priority, preview, 📝documentation/product

#80 🚧Refactor unit test assertions
  PackageMonster.sln.DotSettings
  PackageMonster/Program.cs
  Testing/PackageMonsterTests/Guards/EnsureThatTests.cs
Labels: low priority, preview, tech debt

#82 🚀Preview Release
  .vscode/release-notes.code-snippets
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.1.md
  PackageMonster/PackageMonster.csproj
Labels: 🚀Preview Release
