Repository KinsonDigital/PackageMonster, pull requests merged in 2023-08, with the labels that each got.

#102 🚧Adjust release workflow input
  .github/workflows/add-new-issue-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sync-bot.yml
  .github/workflows/sync-issue-to-pr.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/unit-test-status-check.yml
Labels: low priority, preview, ♻️cicd

#118 🚧Lock version of MOQ
  README.md
  Testing/PackageMonsterTests/PackageMonsterTests.csproj
Labels: high priority, 📦dependency update

#126 🚧Adjust workflow trigger
  .github/workflows/add-new-item-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/sync-bot.yml
  .github/workflows/sync-issue-to-pr.yml
  .github/workflows/sync-pr-to-issue.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/unit-test-status-check.yml
Labels: high priority, ♻️cicd
